{% set name = "beniget" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75554b3b8ad0553ce2f607627dad3d95c60c441189875b98e097528f8e23ac0c

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - gast >=0.5.0,<0.6.0
    - python >=3.6

test:
  imports:
    - beniget
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/serge-sans-paille/beniget
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extract semantic information about static Python code

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - serge-sans-paille
