{% set name = "beniget" %}
{% set version = "0.4.2.post1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0258537e65e7e14ec33a86802f865a667f949bb6c73646d55e42f7c45a052ae

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - gast >=0.5.0,<0.6.0
    - python >={{ python_min }}

test:
  imports:
    - beniget
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/serge-sans-paille/beniget
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extract semantic information about static Python code

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - serge-sans-paille
